
services:
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm run nodemon"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app

  db:
    image: postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata2
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: manga_3_test
    volumes:
      - pg-data:/var/lib/postgresql/data

  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  nginx:
    image: nginx
    volumes:
     - ../static:/usr/share/nginx/html/
     - ./nginx:/etc/nginx/templates
    ports:
     - "8081:80"
    environment:
     - NGINX_HOST=microservice.com
     - NGINX_PORT=80

volumes:
  pg-data: